### ISSUE TITLE
2016 Offseason feature requests

### ISSUE THREAD

**Issue by ndalporto** [BREAD5940/FRC-2016-BREAD-Codebase#16]
I know I've already talked to some of you, but I wanted to put all of the feature requests I have in a centralized location. 

Here goes it:
-   Controller vibrates for one second upon the ball entering intake
-  Ceanup smart dashboard (ex.  Removing nonrelevant info boxes, centralizing layout, etc.)
-  Visual indicator in smart dashboard as to what gear robot is in (ex.  Display in some attention grabbing fashion whether the robot is in high or low gear)
- Clean up code and comment

**Comment by ndalporto** [comment]
Also, let's try to integrate the navX for more precise movement.

**Comment by mbentley124** [comment]
I fixed up the smart dashboard

**Comment by ndalporto** [comment]
Integrate encoders and navX for more precise driving in auto and teleop

**Comment by ndalporto** [comment]
Have a button that reverses the controls.

**Comment by ndalporto** [comment]
I'm gonna call this one closed being that our competition season is over.
